# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 00:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='passwrd',
            new_name='password',
        ),
    ]
